import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
it('renders without crashing1', () => {});
